- hosts: ec2-instances
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_host: <public_ip_address>
    ansible_ssh_private_key_file: <path_to_private_key_file>
  roles:
    - ansible-docker-compose
